//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lego_Inventory_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class brick
    {
        public int brickelementid { get; set; }
        public Nullable<int> brickid { get; set; }
        public string name { get; set; }
        public Nullable<int> typeid { get; set; }
        public Nullable<int> colorid { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual color color { get; set; }
        public virtual type type { get; set; }
    }
}
